<?php
@define("_nameError","Please enter your name");
@define("_nameError1","Invalid name");
@define("_phoneError","Please enter a number");
@define("_phoneError1","invalid phone number");
@define("_emailError","Please enter Email");
@define("_emailError1","Email is not correct format");
@define("_capchaError","Please enter the security code");
@define("_capchaError1","incorrect Security Code");
@define("_titleError","Please enter a title");
@define("_contentError","Please enter the text");
@define("_addressError","Please enter address");
@define("_searchError", "You did not enter a keyword");
@define("_thongtinykhoa","Medical information");	
@define("_Errorcontact","An error has occurred. We have not received your information");
@define("_chonchuyenmuc","You do not select the category");
@define("_vuilongcheckemail","Please check your email to confirm the registration.");
// ------------ Menu -----------------
@define("_trangchu","Home");
@define("_gockhachhang","For customers");
@define("_phanphoi","Distribution");
@define("_doitac","Partners");
@define("_cauchuyen","Golden bee Story");
@define("_phattrienbenvung","SUSTAINABLE DEVELOPMENT");
@define("_vungnguyenlieu","Dairy Development Division");
@define("_truyenthong","Media");
define("_thongtinlienlac","Contact information");
@define("_dangkynhantin","Sign up for newsletter");
@define("_danhsachchuyenmuc","List categories");
@define("_yeucau","Request");
@define("_nhacungcap","Supplier");
@define("_sanphamhienco","Products available");
@define("_vechungtoi","About us");
@define("_lienketnhanh","Quick Links");

@define("_thamdo","examined");
@define("_ykien","reviews");

@define("_cauhoithuonggap","Questions normally seen");
@define("_thamgiadaily","FRANCHISE");
@define("_cosohatang","Infrastructure");
@define("_tenfile","Name File");
@define("_gioithieu","About us");
@define("_suachua","Repair");
@define("_phukien","Accessories");
@define("_sanpham","Products");
@define("_hoachat","Chemistry");
@define("_hoatdong","Activities");
@define("_banggia","Price tag");
@define("_tintuc","News");
@define("_sukien","Event");
@define("_filebanggia","Click download price list");
@define("_thegioi","World");
@define("_nutrang","Jewellery");
@define("_maimei","Code IMEI");

@define("_hosonangluc","Competency Profile");
@define("_tintucsukien","NEWS & EVENTS");
@define("_dichvu","Services");
@define("_dichvubaove","Security Services");
@define("_danhmucdichvu","Services Catalog ");
@define("_dichvuphim","movie Services");
@define("_khachsan","Hotel");
@define("_nhahangtieccuoi","wedding reception restaurant");
@define("_khuyenmai","Promotions");
@define("_chitietkhuyenmai","Promotion Details");
@define("_khuyenmaikhac","Other Promotions");
@define("_lienhe","Contact");
@define("_valuetk","Enter search keywords ...");
@define("_timkiem","Search");
@define("_valuelt","Enter your email ...");
@define("_dangluc","Last time");
@define("_daxem","Views");
@define("_xemtiep","Veiw detail");
@define("_ma","Code");
@define("_gia","Price");
@define("_chitiet","Details");
@define("_sanphamtieubieu","Featured Products");
@define("_sanphamvip", "Products Vip");
@define("_sanphambanchay","Bestsellers");
@define("_tintucnoibat","News Highlights");
@define("_chitiettin","Detailed Information");
@define("_chitietsanpham","product details");
@define("_chitietdichvu","Service Details");
@define("_sanphamcungloai","Other products");
@define("_congtrinhcungloai","Other Buildings");
@define("_giaban","Price");
@define("_luotxem","view");
@define("_ykienkhachhang","Customer feedback");
@define("_thongketruycap","Visitor");
@define("_online","Online");
@define("_luottruycap","Counter");
@define("_hotrotructuyen","online support");
@define("_danhchoquangcao","For advertisers");
@define("_ghichuthem","Additional Notes");
@define("_danhmucnhacungcap","supplier list");
@define("_khachhanglondahoptac","Large customers have cooperated");
@define("_tienich","Utilities");
@define("_lichvannien","Lunar Calendar");
@define("_thongketruycap","Counter");
@define("_thuonghieu","trademark");
@define("_thongtinthamkhao","Reference Information");

@define("_duandamoinhat","latest project");
@define("_duandathuchien","project was implemented");
@define("_xemtatca","View All");
@define("_lienketwebsite","Web links");
@define("_bando","Map");
@define("_nhaptensp","Enter keywords to search");
@define("_timkiem","Search");
@define("_cacbaikhac","The other post");
// -------- ------------- Contact
@define("_gui","Send");
@define("_nhaplai","Reset");
@define("_diachi","Address");
@define("_Email","Email");
@define("_tieude","title");
@define("_noidung","Content");
@define("_dienthoai","Phone");
@define("_hovaten","Full name");
@define("_hoten","Full name");
@define("_ykiendonggop","Content");
@define("_ghichu","You can contact us from this website by filling the contact information on the form below. We will contact you as soon as possible. Xin sincere thanks .");
@define("_mauthietke","designs");
@define("_chitietmauthietke","detail design");
@define("_mauthietkekhac","other designs");
@define("_tuyendung","Recruitment");
@define("_nhaxuong", "Factory");
@define("_thietbi", "Equipment");
@define("_thongtin", "Information");
@define("_thongtindoitac", "Information Partners");
@define("_thongtinchitiet", "Information Detail");
@define("_noidungchitiet", "Content Detail");
@define("_hinhanh","Image");
@define("_chitiethinhanh","detail images");
@define("_hinhanhkhac","Other images");
@define("_tongtruycap","Total Access");
@define("_sanphamcongty","Company Products");
@define("_sanphamdep","Beauty Products");
@define("_masp","Code");

//----------------------------------USER -----------------//

@define("_batbuoc1","Information with");
@define("_batbuoc2","are required fields, need to enter.");
@define("_ngaysinh","Date of birth"); 
@define("_thongtingiaohang","Information Delivery"); 
@define("_tinhthanh","Town / City");
@define("_chontinhthanh","Choose Town / City"); 
@define("_quanhuyen","County / District"); 
@define("_chonquanhuyen","Choose County / District");
@define("_sodienthoai","Phone numbers"); 
@define("_dieukhoandangky","Terms of registration"); 
@define("_chapnhandieukhoan","I have read and agree with all the terms above."); 
@define("_chuadongydieukhoan","You do not agree with the terms that we offer."); 
@define("_xinvuilongnhapemail","Please enter your email."); 
@define("_xinnhapmatkhau","Please enter your password."); 
@define("_xinnhaplaimatkhau","Please enter your password."); 
@define("_haimatkhaukhonggiong","The passwords are not the same."); 
@define("_xinchonngaysinh","Please choose the date of birth."); 
@define("_dangkythanhcong","Account Registration success!"); 
@define("_loiemaildaco","Error! This e-mail there!"); 
@define("_vuilongquaylaisau","An error occured! Please check back later!"); 
@define("_loinhapmasai","Error! Enter the captcha code wrong!"); 
@define("_khachhangmoi","New Customer"); 
@define("_loiichdangky","By creating an account you will be able to shop faster, be updated on the status of an order, and keep track of the orders you have previously made."); 
@define("_banchuacotaikhoan","Do not have an account?"); 
@define("_dangkyngay","Register now !");
@define("_dangnhapthanhcong","Login successful !"); 
@define("_loitaikhoan","Error! Account information is incorrect!"); 
@define("_laylaimatkhauerro","Retrieve password succeed! Please check your email!"); 
@define("_loithongtinemail","Error! Information incorrect email."); 
@define("_laylaimatkhau","Password retrieval"); 
@define("_doitaikhoanthanhcong","Change account information successfully!"); 

// ------------ Cart ----------------- //
@define ("_giohang2" , "Do you want to remove products from cart" );
@define ("_giohang3" , "Cart will be wiped clean, you can be sure this" );
@define("_soluongsanpham","Number of products");
@define("_tongsoluong","Total quantity");
@define("_tongtien","Total money");
@define("_donhang","Orders");
@define("_datmua","Order");
@define("_giohang","cart");
@define("_capnhatgh","Update");
@define("_nguoinhan","Recipient");
@define("_dangnhaptaikhoankhac","Sign in with another account");
@define("_thaydoi","To change");
@define("_dangnhapcotaikhoan","Login information if an account");
@define("_chuacotaikhoan","No account");
@define("_stt","No");
@define("_ten","name");
@define("_soluong","Number");
@define("_thanhtien","Amount");
@define("_xoa","Delete");
@define("_xoatatca","Clear All");
@define("_tong","Total");
@define("_tieptucmuahang","continue shopping");
@define("_dathang","Order");
@define("_emptycart","There are no items in the cart !");
@define("_vidukiemtradonhang","Please enter the code line check (eg TGNT-12345 - Enter a part number 12345 does not enter part TGNT-)");
@define("_luu","Save"); 
// ------------ Payment ----------------- //
@define ("_thanhtoan14" , "Your order has been sent. <br> Thanks" );
@define ("_thanhtoan15" , "Your order has been saved. <br> Thanks" );
@define ("_thanhtoan16" , "Your order has been sent" );
@define("_thanhtoan","Payment");
@define("_thongtindathang","Ordering Information");
@define("_ngaygiao","date");
@define("_hinhthucthanhtoan","Payment method");
@define("_tttienmat","Cash Payment");
@define("_ttnganhang","Payment via bank");
@define("_ghichu","Note");
@define("_lamlai","Redo");
@define("_danhmucsanpham","Product Category");
@define("_danhmucthietbi","Equipment Category");
@define("_danhmucphukien","Accessories Category");
@define("_danhmuccongtrinh","Buildings Category");
@define("_danhmuchoachat","Chemistry Category");
@define("_danhmucduan","Project Category");
@define("_quangcao","Advertising");
@define ("_thulienhetuweb", "Message from website contact" );


@define("_hoidap","FAQ");
@define("_chinhsach","policy");
@define("_chinhsachmuahang","Policy buy product");
@define("_datcauhoi","Question");
@define("_hoi","Question");
@define("_dap","A");
@define("_bophanchamsockhachhang","customer service department");
@define("_binhluan","Comments");
@define("_dieukhoanbl","Only accept comments marked by Vietnamese , irregularities comments will be deleted .");
@define("_xemthembl","More comments ...");
@define("_xemthem","More view");
@define("_dangbl","comment form");
@define("_saimxn","Verification Code is incorrect !");
@define("_loi","Please perform the operation error occurred !");
@define("_maxn","Verification");
@define("_noidungbl","Please enter the text comment");
@define("_tonggia","Total");
@define("_tonggiatridonhang","The total value of orders:");
@define("_thongtinlienhe","Contact Information");
@define("_danhxung","Title");
@define("_thongtinbatbuoc","As part of the required information");
@define("_noidungdangcapnhat","Content is updating ...");
@define("_khongtimthayketqua","No results were found !!! Please enter the correct value looking ...");
@define("_nhapthongtin","Please enter full information !");
@define("_coloixayra","An error occurred , please leave !");
@define("_guithanhcong","Send your success ! <br/> We will contact you soon");
@define("_emailtontai","email already exists !");
@define("_anh","Mr");
@define("_chi","Miss");
@define("_sanphammoi","New Product");
@define("_sanphamsapve","Product upcoming");
@define("_thongketuan","Statistics week");
@define("_thongkethang","Statistics months");
@define("_thoitiet","weather");
@define("_ngoaite","rate of exchange");
@define("_chungkhoan","Stock Information");
@define("_vannien","Lunar Calendar");
@define("_contact","Contact");
@define("_lienket","Link");
@define("_ketnoi","Connect with Us");
@define("_mota","description");
@define("_thongtincongty","Company Info");
@define("_dichvubaohanh","Services - Warranty");
@define("_giogiaclamviec","Hours worked");
@define("_thongtindaily","Information Agent");
@define("_thongsokythuat","Specifications");
@define("_giaiphapchongtham","Waterproofing Solution");
@define("_hotroonline","Online Support");
@define("_homnay","Today");
@define("_daonline","Total Access");
@define("_xinchao","Welcome");
@define("_dangxuat","Logout");
@define("_tongcong","Total");
@define("_chuacosanphamtronggiohang","No product in cart");
@define("_chinhsachcongty","company policy");
@define("_hotrokhachhang","Customer Support");
@define("_sodienthoaihotlinehotro","Support Hotline Phone Number");
@define("_chuyentienquanganhang","transfer money through bank");
@define("_huongdanduongdi","Directions");
@define("_phuongthucthanhtoan","Payment Method");
@define("_hotrobanhang","sales support");
@define("_hotrogiaonhan","Support delivery");
@define("_trungtambaohanh","Service Center");
@define("_sapxep","Sort");
@define("_giatangdan","Price Ascending");
@define("_moinhat","latest");
@define("_tinhtrang","Status");
@define("_baohanh","warranty");
@define("_xuatxu","origin");
@define("_giatruocday","previous price");
@define("_tietkiem","Save");
@define("_thongtinsanpham","Product Information");
@define("_huongdansudung","Manual");
@define("_cothebancungthichsanphamnay","You might also like this product");
@define("_giaohangthutien","Delivery & Collection");
@define("_chuyenkhoancacnganhang","bank transfers");
@define("_congthanhtoannganluong","Payment Gateway funding amount");
@define("_topsanpham","Top Product");
@define("_bannhieu","Sell more");
@define("_xemnhieu","Most Viewed");
@define("_danhgia","Assessment");
@define("_thongtinhuuich","Useful Information");
@define("_muasp","Buy Product");
@define("_mabaove","Security code");
@define("_dangky","Register");
@define("_dangnhap","Login");
@define("_dangkythanhvien","Register");
@define("_thongtintaikhoan","Account Information");
@define("_matkhau","Password");
@define("_xacnhanmatkhau","Confirm Password");
@define("_thongtinkhachhang","Customer Information");
@define("_dangkytaikhoan","account registration");
@define("_taikhoan","Account");
@define("_quenmatkhau","Forgot password");
@define("_dangkyngay","Sign up now");

@define("_xacnhan","Confirm");
@define("_camonbandadanhgiasp","Thank you for evaluating this product !");
@define("_banco","You");
@define("_banchuanhaptukhoa","You did not enter keywords"); 
@define("_sanphamtronggiohang","basket product");
@define("_conhang","In stock");
@define("_capnhat","Update");
@define("_tienhanhdathang","Proceed to order");
@define("_thongtinthanhtoan","Account Information");
@define("_bancomotmagiamgia","You have a discount code");
@define("_sudung","Use");
@define("_thongtindonhang","Order Information");
@define("_diachigiaohang","Shipping Address");
@define("_hotencuaban","your name");
@define("_nhaduongphuongquantp","House number, Street, County, City");
@define("_chuyenkhoan","Transfer");
@define("_vidientunganluong","Nganluong");
@define("_thanhtoanthenoidia","domestic card Payment");
@define("_thanhtoanthequocte","international payment card");
@define("_chucnangdangduocxaydung","function under construction");
@define("_hoantatthanhtoan","Complete Payment");
@define("_nameErrorNH","Please enter the consignee name");
@define("_phoneErrorNH","Please enter the phone number of the consignee");
@define("_phoneErrorNH1","consignee's telephone number is not valid");
@define("_emailErrorNH","Email Please enter the consignee");
@define("_emailErrorNH1","Email consignee incorrect format");
@define("_addressErrorNH","Please enter the delivery address");
@define("_xacnhanthanhcong","Validation successful");
@define("_quayvetrangchu","Go back home");
@define("_daycunglathongtinnguoinhan","This is also the recipient of the information");
@define("_tratienkhinhanhang","Pay on delivery");
@define("_vidientupaypal","Paypal");
@define("_bancomotmagiamgia","You have a discount code");
@define("_kiemtradonhang","Check Order");
@define("_kiemtraimei","Check IMEI");
@define("_vidunhapimei","Please enter the code IMEI inside baskets jewelry");
@define("_nhapmaimei","Enter the IMEI code");
@define("_chuanhapmaimei","Unknown IMEI code");
@define("_thongtincanhan","Personal Information");
@define("_thaydoimatkhau","Change Password");
@define("_chonthemsanpham","Product Option");
@define("_hotrothanhtoanqua","Support payments through");
@define("_magiamgia","discount code");
@define("_dienmagiamgiavaoday","Enter the discount code here");
@define("_phivanchuyen","Shipping Costs");
@define("_mienphi","Free");
@define("_dabaogomthue","Tax Included");
@define("_hoac","Or");
@define("_trovedanhmuc","Return to list");
@define("_dangxuatthanhcong","Logout successful");
@define("_nhomatkhau","Remember Me");
@define("_dangkyhoacdangnhapvaotaikhoancuaban","Register or log into your account");
@define("_khachhangdadangky","Registered Customers");
@define("_banlakhachhangmoichuacotaikhoan","You are a new customer without account");
@define("_dangkyvamuahang","Registration and purchase");
@define("_banchuacodonhangnao","You do not have any orders");
@define("_ngaydat","Order date");
@define("_madonhang","Order Code");
@define("_nhapmadonhang","Enter orders");
@define("_chuanhapmadonhang","You do not enter an order !!!");
@define("_xem","View");
@define("_huydonhang","Cancel Order");
@define("_bancothatsuhuydonhangnay","Do you really want to cancel this order");
@define("_huydonhangnay","Cancel this order");
@define("_thongtinnguoidathang","ordering the Information");
@define("_thongtinnguoinhanhang","consignee Information");
@define("_quaylai","Back");
@define("_chitietdonhang","Order detail");
@define("_coupleError","Please enter discount code");

@define("_linhvuchoatdong", "Practices");
@define("_linhvuccongty", "Practices Companny");
@define("_luatsu", "Associates");
@define("_tuvan", "FAQS");
@define("_thuvien", "Library");
@define("_thongke", "Visitor");
@define("_lienhevoichungtoi", "Contact us");
@define("_theodoihoso", "File code");
@define("_nhaphovaten", "Enter your Name");
@define("_nhapmahoso", "Enter file code");
@define("_mahoso", "File name");
@define("_banchuanhapmahoso", "You did not enter a code file");
@define("_guicauhoidenchungtoi", "Send my question to them");
@define("_guicauhoi", "Send Question");
@define("_cauhoi", "Question");
@define("_dong", "Close");
@define("_docthem", "Read more");
@define("_tinkhac", "Other Information");
@define("_cosohatangkhac","Other Infrastructure");
@define("_filedinhkem", "Attachments");
@define("_hosoError", "Profile does not exist");
@define("_email","Email");
@define("_kiemtra","Check");
@define("_tukhoa","Keyword");
@define("_hethongdaily","Dealer network");
@define("_khongcodailynaookhuvucnay","No dealer in this area !");
@define("_duan", "Project");
@define("_congtrinh", "Buildings");
@define("_congtrinhtieubieu","WORKS");
@define("_maunha", "Model home");
@define("_kientruc", "Architecture");
@define("_congtrinhnoibat", "Outstanding work");
@define("_duannoibat", "Outstanding project");
@define("_maunhadep", "Beautiful Model home");
@define("_danhmuccongtrinh", "Project list");
@define("_tienichonline", "Online utility");
@define("_dubaothoitiet", "Weather project");
@define("_giavang", "Gold price");
@define("_lienketweb", "Web Links");
@define("_doitaccuachungtoi", "Our Partners");
@define("_xemchitiet", "Details");
@define("_xemchitietsanpham","Details Product");
@define("_caccongtrinhkhac", "other works");
@define("_cacmaunhakhac", "Another model home");
@define("_chonlienket", "Select the link");
@define("_cacduankhac","Other projects");
@define("_baotribaoduong", "maintenance");
@define("_cungungthietbivattu", "Supply of equipment and materials");
@define("_cacduan", "projects");
@define("_logodoitac", "Logo partner");

@define("_hinhanhdoitac", "Photo partner");
@define("_hinhanhduan","Album Project");
@define("_hinhanhsanpham","Album Product");


@define("_guibaogiathanhcong", "Send a request for quotation successful, we will contact you soon!"); 
@define("_temnhanmac", "Stamp label"); 
@define("_quangcaokhuyenmai", "Advertising - Promotions"); 
@define("_giaiphapchonggia", "Anti-counterfeiting solution"); 
@define("_giacong", "processing"); 
@define("_mmtuvan", "MM Consultant"); 
@define("_giay", "License"); 
@define("_kimloai", "Metal"); 
@define("_loaikhac", "Other"); 
@define("_inluainluoi", "Screen printing (screen printing)"); 
@define("_incuon", "Reel"); 
@define("_inbenmau", "Print durable color");

@define("_veminhman", "About Minh Man"); 
@define("_guiyeucaubaogia", "Request for Quotation"); 
@define("_huongdanguifile", "Guide to Sending file"); 
@define("_quytrinhsanxuatmotsanpham", "Manufacturing process a product"); 
@define("_giaohangnhantien", "Delivery receipt money"); 
@define("_mienphigiaohang", "Free delivery"); 
@define("_nguyenlieuphuhop", "Suitable materials"); 
@define("_congngheapdung", "Applied technology"); 
@define("_toiuusanpham", "Optimal product"); 
@define("_khachhang", "Customer & Partner "); 
@define("_homqua", "Yesterday"); 
@define("_ngaydang", "Date post"); 
@define("_hantuyendung", "Deadline"); 
@define("_cactintuyendungkhac", "The Other Jobs"); 
@define("_congty", "Company"); 
@define("_congtyError", "Please enter your company");
@define("_cactingioithieukhac","The Other About");

?>