<?php
@define("_nameError","Vui lòng nhập họ tên");
@define("_nameError1","Họ tên không hợp lệ");
@define("_phoneError","Vui lòng nhập số điện thoại");
@define("_phoneError1","Số điện thoại không hợp lệ");
@define("_emailError","Xin vui lòng nhập Email");
@define("_emailError1","Email không đúng định dạng");
@define("_capchaError","Vui lòng nhập mã bảo vệ");
@define("_capchaError1","Mã bảo vệ không đúng");
@define("_titleError","Xin nhập tiêu đề");
@define("_contentError","Xin nhập nội dung");
@define("_addressError","Xin nhập địa chỉ");
@define("_searchError","Bạn chưa nhập từ khóa tìm kiếm");
@define("_Errorcontact","Có lỗi xảy ra. Chúng tôi chưa nhận được thông tin của bạn");
@define("_chonchuyenmuc","Bạn chưa chọn chuyên mục");
@define("_vuilongcheckemail","Vui lòng check email để xác nhận đăng kí.");
//------------ Menu -----------------
@define("_trangchu","Trang chủ");
@define("_gockhachhang","Góc khách hàng");
@define("_phanphoi","Phân phối");
@define("_doitac","Đối tác");
@define("_yeucau","Yêu cầu");
@define("_nhacungcap","Nhà cung cấp");
@define("_sanphamhienco","Sản phẩm hiện có");
@define("_vechungtoi","Về chúng tôi");
@define("_lienketnhanh","Liên kết nhanh");

@define("_cauchuyen","Câu chuyện Golden bee");
@define("_phattrienbenvung","Phát triển bền vững");
@define("_vungnguyenlieu","Vùng nguyên liệu");
@define("_truyenthong","Truyền thông");
@define("_thongtinlienlac","Thông tin liên lạc");
@define("_dangkynhantin","Đăng ký nhận bản tin");
@define("_danhsachchuyenmuc","Danh sách các chuyên mục");




@define("_cauhoithuonggap","Câu hỏi thường gặp");
@define("_thamgiadaily","THAM GIA ĐẠI LÝ");
@define("_gioithieu","Giới thiệu");
@define("_sanpham","Sản phẩm");
@define("_hoachat","Hóa chất");
@define("_cosohatang","Cơ sở hạ tầng");
@define("_camnang","Cẩm nang");
@define("_thietke","Thiết kế");
@define("_thegioi","Thế giới");
@define("_nutrang","Nữ trang");
@define("_xemnhanh","Xem nhanh");
@define("_huongdan","Hướng dẫn");
@define("_filebanggia","Click download bảng giá");

@define("_tintuc","Tin tức");
@define("_sukien","Sự kiện");

@define("_thamdo","Thăm dò");
@define("_ykien","Ý kiến");

@define("_hosonangluc","Hồ sơ năng lực");
@define("_banggia","Bảng giá");
@define("_hoatdong","Hoạt động");
@define("_tintucsukien","Tin tức & Sự kiện");
@define("_suachua","Sửa chữa");
@define("_phukien","Phụ kiện");
@define("_tenfile","Tên File");
@define("_dichvu","Dịch vụ");
@define("_dichvubaove","Dịch vụ bảo vệ");
@define("_danhmucdichvu","Danh mục dịch vụ");	
@define("_thongtinykhoa","Thông tin y khoa");	
@define("_thuonghieu","Thương hiệu");
@define("_thongtinthamkhao","Thông tin tham khảo");
@define("_maimei","Mã IMEI");
 


@define("_dichvuphim","Dịch vụ phim");	
@define("_khachsan","Khách sạn");	
@define("_nhahangtieccuoi", "Nhà hàng tiệc cưới");	
@define("_khuyenmai", "Khuyến mãi");
@define("_chitietkhuyenmai", "Chi tiết khuyến mãi");
@define("_khuyenmaikhac", "Khuyến mãi khác");
@define("_lienhe","Liên hệ");
@define("_valuetk","Nhập từ khóa...");
@define("_timkiem","Tìm Kiếm");
@define("_valuelt","Nhập email của bạn...");
@define("_dangluc","Đăng lúc"); 
@define("_daxem","Đã xem"); 
@define("_xemtiep","Xem tiếp"); 
@define("_ma","Mã"); 
@define("_gia","Giá"); 
@define("_chitiet", "Chi tiết");
@define("_sanphamtieubieu", "Sản phẩm nổi bật");
@define("_sanphamvip", "Sản phẩm Vip");
@define("_sanphambanchay", "Sản phẩm bán chạy");
@define("_tintucnoibat", "Tin tức nổi bật");
@define("_chitiettin", "Chi tiết tin");
@define("_chitietsanpham", "Chi tiết sản phẩm");
@define("_chitietdichvu", "Chi tiết dịch vụ");
@define("_sanphamcungloai", "Sản phẩm cùng loại");
@define("_congtrinhcungloai", "Công trình cùng loại");
@define("_giaban", "Giá bán");
@define("_luotxem", "Lượt xem");
@define("_ykienkhachhang", "Ý kiến khách hàng");
@define("_thongketruycap","Thống kê truy cập");
@define("_online","Đang online");
@define("_luottruycap","Lượt truy cập");
@define("_hotrotructuyen","Hỗ trợ trực tuyến");
@define("_danhchoquangcao","Dành cho quảng cáo");
@define("_ghichuthem","Ghi chú thêm");
@define("_danhmucnhacungcap","Danh mục nhà cung cấp");
@define("_khachhanglondahoptac","Khách hàng lớn đã hợp tác");
@define("_tienich","Tiện ích");
@define("_lichvannien", "Lịch vạn niên");
@define("_thongketruycap","Thống kê truy cập");
@define("_duandamoinhat","Dự án mới nhất");
@define("_duandathuchien","Dự án đã thực hiện");
@define("_xemtatca","Xem tất cả");
@define("_lienketwebsite","Liên kết website");
@define("_bando","Bản đồ");
@define("_nhaptensp","Nhập từ khóa để tìm kiếm");
@define("_timkiem","Tìm kiếm");
@define("_cacbaikhac","Các bài đăng khác");


@define("_danhmuc","Danh mục");

//------------- Contact --------
@define("_gui"," Gửi ");
@define("_nhaplai"," Nhập lại ");
@define("_diachi","Địa chỉ");
@define("_email", "Email");
@define("_tieude", "Tiêu đề");
@define("_noidung", "Nội dung");
@define("_dienthoai","Điện thoại");
@define("_hovaten","Họ và tên");
@define("_hoten","Họ và tên");
@define("_ykiendonggop", "Nội dung");
@define("_ghichu","Quý khách có thể liên hệ với chúng tôi từ website này bằng cách điền đầy đủ những thông tin vào form liên hệ bên dưới. Chúng tôi sẽ liên hệ với Quý khách trong thời gian sớm nhất. Xin chân thành cảm ơn.");
@define("_mauthietke","Mẫu thiết kế");
@define("_chitietmauthietke","Chi tiết mẫu thiết kế");
@define("_mauthietkekhac","Mẫu thiết kế khác");
@define("_tuyendung", "Tuyển dụng");
@define("_nhaxuong", "Nhà xưởng");
@define("_thietbi", "Thiết bị");

@define("_thongtin", "Thông Tin");
@define("_thongtindoitac", "Thông tin một số đối tác");
@define("_thongtinchitiet", "Thông tin chi tiết");
@define("_noidungchitiet", "Nội dung chi tiết");
@define("_hinhanh", "Hình ảnh");
@define("_chitiethinhanh", "Chi tiết hình ảnh");
@define("_hinhanhkhac", "Hình ảnh khác");
@define("_tongtruycap", "Tổng truy cập");
@define("_sanphamcongty", "Sản phẩm công ty");
@define("_sanphamdep", "Sản phẩm đẹp");
@define("_masp", "Mã Sản Phẩm");


//----------------------------------THÀNH vIÊN -----------------//

@define("_batbuoc1","Thông tin có");
@define("_batbuoc2","là bắt buộc nhập, cần phải nhập");

@define("_mabaove","Mã bảo vệ"); 
@define("_dangky","Đăng ký"); 
@define("_dangkythanhcong","Đăng ký tài khoản thành công !"); 
@define("_loiemaildaco","Lỗi ! Email này đã có !"); 
@define("_vuilongquaylaisau","Có lỗi xảy ra ! Vui lòng quay lại sau !"); 
@define("_loinhapmasai","Lỗi ! Nhập mã captcha sai!");
@define("_loitaikhoan","Lỗi ! Thông tin tài khoản không chính xác !"); 
@define("_dangnhap","Đăng nhập"); 
@define("_dangnhapthanhcong","Đăng nhập thành công !"); 
@define("_dangkythanhvien","Đăng ký thành viên"); 
@define("_thongtintaikhoan","Thông tin tài khoản"); 
@define("_matkhau","Mật khẩu"); 
@define("_xacnhanmatkhau","Xác nhận mật khẩu"); 
@define("_ngaysinh","Ngày sinh"); 
@define("_thongtingiaohang","Thông tin giao hàng"); 
@define("_thongtinkhachhang","Thông tin khách hàng"); 
@define("_dangkytaikhoan","Đăng ký tài khoản"); 
@define("_taikhoan","Tài khoản"); 
@define("_quenmatkhau","Quên mật khẩu"); 
@define("_dangkyngay","Đăng ký ngay"); 
@define("_xacnhan","Xác nhận"); 
@define("_loiichdangky","Bằng cách tạo ra một tài khoản bạn sẽ có thể mua sắm nhanh hơn, được cập nhật về tình trạng của một đơn hàng, và theo dõi các đơn đặt hàng bạn đã thực hiện trước đó."); 
@define("_banchuacotaikhoan","Bạn chưa có tài khoản ?"); 
@define("_dangkyngay","Đăng ký ngay !"); 

@define("_tinhthanh","Tỉnh / Thành"); 
@define("_chontinhthanh","Chọn Tỉnh / Thành"); 
@define("_quanhuyen","Quận / Huyện"); 
@define("_chonquanhuyen","Chọn Quận / Huyện"); 
@define("_sodienthoai","Số điện thoại"); 
@define("_dieukhoandangky","Điều khoản đăng ký"); 
@define("_chapnhandieukhoan","Tôi đã đọc và đồng ý với tất cả các điều khoản ở trên."); 
@define("_chuadongydieukhoan","Bạn chưa đồng ý với các điều khoản mà chúng tôi đưa ra."); 
@define("_xinvuilongnhapemail","Xin vui lòng nhập email."); 
@define("_xinnhapmatkhau","Xin nhập mật khẩu."); 
@define("_xinnhaplaimatkhau","Xin nhập lại mật khẩu."); 
@define("_haimatkhaukhonggiong","Hai mật khẩu không giống nhau."); 
@define("_xinchonngaysinh","Xin chọn ngày sinh."); 
@define("_khachhangmoi","Khách Hàng Mới"); 

@define("_laylaimatkhauerro","Lấy lại mật khẩu thành công ! Xin vui lòng kiểm tra email !"); 
@define("_loithongtinemail","Lỗi ! Thông tin email không chính xác ."); 
@define("_laylaimatkhau","Lấy lại mật khẩu"); 
@define("_doitaikhoanthanhcong","Thay đổi thông tin tài khoản thành công !"); 
@define("_luu","Lưu"); 


//------------ Giỏ Hàng -----------------//
@define ("_giohang2" , "Bạn có muốn xóa sản phẩm khỏi giỏ hàng" );
@define ("_giohang3" , "Giỏ hàng sẽ bị xóa sạch, bạn có chắc chắn việc này" );
@define("_datmua","Đặt mua");
@define("_giohang","Giỏ hàng");
@define("_capnhatgh","Cập nhật");
@define("_stt","STT");
@define("_ten","Tên");
@define("_soluong","Số lượng");
@define("_soluongsanpham","Số lượng sản phẩm");
@define("_tongsoluong","Tổng số lượng");
@define("_tongtien","Tổng tiền");
@define("_thanhtien","Thành tiền");
@define("_xoa","Xóa");
@define("_xoatatca","Xóa tất cả");
@define("_tong","Tổng");
@define("_tieptucmuahang","Tiếp tục mua hàng");
@define("_dathang","Đặt hàng");
@define("_emptycart","Không có sản phẩm nào trong giỏ hàng!");
@define("_vidukiemtradonhang","Vui lòng nhập mã đơn hàng cần kiểm tra (VD: TGNT-12345 - Chỉ nhập phần số 12345 không nhập phần TGNT-)");
//------------ Thanh Toán -----------------//
@define ("_thanhtoan14" , "Đơn hàng của bạn đã được gửi.<br>Cảm ơn" );
@define ("_thanhtoan15" , "Đơn hàng của bạn đã được lưu.<br>Cảm ơn" );
@define ("_thanhtoan16" , "Đơn hàng của bạn đã được gửi" );
@define("_thanhtoan","Thanh toán");
@define("_donhang","Đơn hàng");
@define("_thongtindathang","Thông tin đặt hàng");
@define("_ngaygiao","Ngày giao");
@define("_hinhthucthanhtoan","Hình thức thanh toán");
@define("_tttienmat","Thanh toán bằng tiền mặt");
@define("_ttnganhang","Thanh toán qua ngân hàng");
@define("_ghichu","Ghi chú");
@define("_lamlai","Làm lại");
@define("_nguoinhan","Người nhận");
@define("_dangnhaptaikhoankhac","Đăng nhập với tài khoản khác");
@define("_dangnhapcotaikhoan","Thông tin đăng nhập nếu có tài khoản");
@define("_chuacotaikhoan","Chưa có tài khoản");
@define("_thaydoi","Thay đổi");
@define("_danhmucsanpham","Danh mục sản phẩm");
@define("_danhmucthietbi","Danh mục thiết bị");
@define("_danhmucphukien","Danh mục phụ kiện");
@define("_danhmuccongtrinh","Danh mục công trình");
@define("_danhmuchoachat","Danh mục hóa chất");
@define("_danhmucduan","Danh mục dự án");
@define("_quangcao","Quảng cáo");
@define("_hoidap","Hỏi đáp");
@define("_chinhsach","Chính sách");
@define("_chinhsachmuahang","Chính sách mua hàng");
@define("_datcauhoi","Đặt câu hỏi");
@define("_hoi","Hỏi");
@define("_dap","Đáp");
@define("_bophanchamsockhachhang","Bộ phận chăm sóc khách hàng");
@define("_binhluan","Bình luận");
@define("_dieukhoanbl","Chỉ chấp nhận bình luận bằng tiếng Việt có dấu, những bình luận sai qui định sẽ bị xóa.");
@define("_xemthembl","Xem thêm bình luận...");
@define("_xemthem","Xem thêm");
@define("_dangbl","ĐĂNG BÌNH LUẬN");
@define("_saimxn","Mã xác nhận không chính xác!");
@define("_loi","Vui lòng thực hiện lại thao tác có lỗi xảy ra!");
@define("_maxn","Mã xác nhận");
@define("_noidungbl","Vui lòng nhập nội dung bình luận");
@define("_tonggia","Tổng giá");
@define("_tonggiatridonhang","Tổng giá trị đơn hàng:");
@define("_thongtinlienhe","Thông tin liên hệ");
@define("_danhxung","Danh xưng");
@define("_thongtinbatbuoc","Là phần thông tin bắt buộc");
@define("_noidungdangcapnhat","Nội dung đang cập nhật...");
@define("_khongtimthayketqua","Không tìm thấy kết quả !!! Vui lòng nhập đúng giá trị cần tìm...");
@define("_nhapthongtin","Vui lòng nhập đầy đủ thông tin !");
@define("_coloixayra","Có lỗi xảy ra, vui lòng thực hiện lại !");
@define("_guithanhcong","Gửi thông tin thành công!<br/>Chúng tôi sẽ liên hệ sớm với bạn");
@define("_emailtontai","Email này đã tồn tại !");
@define ("_thulienhetuweb", "Thư liên hệ từ website" );
@define("_anh","Anh");
@define("_chi","Chị");
@define("_sanphammoi","Sản phẩm mới");
@define("_sanphamsapve","Hàng sắp về");
@define("_thongketuan","Thống kê tuần");
@define("_thongkethang","Thống kê tháng");
@define("_thoitiet","Dự báo thời tiết");
@define("_ngoaite","Tỷ giá ngoại tệ");
@define("_chungkhoan","Thông tin chứng khoán");
@define("_vannien","Lịch vạn niên");
@define("_contact","Liên hệ");
@define("_lienket","Liên kết");
@define("_ketnoi","Kết nối với chúng tôi");
@define("_mota","Mô tả");
@define("_thongtincongty","Thông tin công ty");
@define("_dichvubaohanh","Dịch vụ - Bảo hành");
@define("_giogiaclamviec","Giờ giấc làm việc");
@define("_thongtindaily","Thông tin đại lý");
@define("_thongsokythuat","Thông số kỹ thuật");
@define("_giaiphapchongtham","Giải pháp chống thấm");
@define("_hotroonline","Hỗ trợ online");
@define("_homnay","Hôm nay");
@define("_daonline","Tổng truy cập");
@define("_xinchao","Xin chào"); 
@define("_dangxuat","Đăng xuất"); 
@define("_tongcong","Tổng cộng"); 
@define("_chuacosanphamtronggiohang","Chưa có sản phẩm trong giỏ hàng"); 
@define("_chinhsachcongty","Chính sách công ty"); 
@define("_hotrokhachhang","Hỗ trợ khách hàng"); 
@define("_sodienthoaihotlinehotro","Số điện thoại Hotline hỗ trợ"); 
@define("_chuyentienquanganhang","Chuyển tiền qua ngân hàng"); 
@define("_huongdanduongdi","Hướng dẫn đường đi"); 
@define("_phuongthucthanhtoan","Phương thức thanh toán"); 
@define("_hotrobanhang","Hỗ trợ bán hàng"); 
@define("_hotrogiaonhan","Hỗ trợ giao nhận"); 
@define("_trungtambaohanh","Trung tâm bảo hành"); 
@define("_sapxep","Sắp xếp"); 
@define("_giatangdan","Giá tăng dần"); 
@define("_moinhat","Mới nhất"); 
@define("_tinhtrang","Tình trạng"); 
@define("_baohanh","Bảo hành"); 
@define("_xuatxu","Xuất xứ"); 
@define("_giatruocday","Giá trước đây"); 
@define("_tietkiem","Tiết kiệm"); 
@define("_thongtinsanpham","Thông tin sản phẩm"); 
@define("_huongdansudung","Hướng dẫn sử dụng"); 
@define("_cothebancungthichsanphamnay","Có thể bạn cũng thích sản phẩm này"); 
@define("_giaohangthutien","Giao hàng & Thu tiền"); 
@define("_chuyenkhoancacnganhang","Chuyển khoản các ngân hàng"); 
@define("_congthanhtoannganluong","Cổng thanh toán ngân lượng"); 
@define("_topsanpham","Top sản phẩm"); 
@define("_bannhieu","Bán nhiều"); 
@define("_xemnhieu","Xem nhiều"); 
@define("_danhgia","Đánh giá"); 
@define("_thongtinhuuich","Thông tin hữu ích"); 
@define("_muasp","Mua sản phẩm"); 
@define("_camonbandadanhgiasp","Cảm ơn bạn đã đánh giá sản phẩm này !"); 
@define("_banco","Bạn có"); 
@define("_banchuanhaptukhoa","Bạn chưa nhập từ khóa"); 
@define("_sanphamtronggiohang","sản phẩm trong giỏ hàng"); 
@define("_conhang","Còn hàng"); 
@define("_capnhat","Cập nhật"); 
@define("_tienhanhdathang","Tiến hành đặt hàng"); 
@define("_thongtinthanhtoan","Thông tin tài khoản"); 
@define("_bancomotmagiamgia ","Bạn có một mã giảm giá"); 
@define("_sudung","Sử dụng"); 
@define("_thongtindonhang","Thông tin đơn hàng"); 
@define("_diachigiaohang","Địa chỉ giao hàng"); 
@define("_hotencuaban","Họ tên của bạn"); 
@define("_nhaduongphuongquantp","Số nhà, Phường, Quận, Thành Phố"); 
@define("_chuyenkhoan","Chuyển khoản"); 
@define("_vidientunganluong","Ví điện tử ngân lượng"); 
@define("_thanhtoanthenoidia","Thanh toán thẻ nội địa"); 
@define("_thanhtoanthequocte","Thanh toán thẻ quốc tế"); 
@define("_chucnangdangduocxaydung","Chức năng đang được xây dựng"); 
@define("_hoantatthanhtoan","Hoàn tất thanh toán"); 
@define("_nameErrorNH","Vui lòng nhập họ tên người nhận hàng");
@define("_phoneErrorNH","Vui lòng nhập số điện thoại người nhận hàng");
@define("_phoneErrorNH1","Số điện thoại người nhận hàng không hợp lệ");
@define("_emailErrorNH","Xin vui lòng nhập Email người nhận hàng");
@define("_emailErrorNH1","Email người nhận hàng không đúng định dạng");
@define("_addressErrorNH","Vui lòng nhập địa chỉ người nhận hàng"); 
@define("_xacnhanthanhcong","Xác nhận thành công"); 
@define("_quayvetrangchu","Quay về trang chủ"); 
@define("_daycunglathongtinnguoinhan","Đây cũng là thông tin của người nhận");
@define("_tratienkhinhanhang","Trả tiền khi nhận hàng");
@define("_vidientupaypal","Ví điện tử Paypal");
@define("_bancomotmagiamgia","Bạn có một mã giảm giá");
@define("_kiemtradonhang","Kiểm tra đơn hàng");
@define("_kiemtraimei","Kiểm tra IMEI");
@define("_vidunhapimei","Xin vui lòng nhập mã IMEI bên trong giỏ trang sức");
@define("_nhapmaimei","Nhập mã IMEI");
@define("_chuanhapmaimei","Chưa nhập mã IMEI");
@define("_thongtincanhan","Thông tin cá nhân");
@define("_thaydoimatkhau","Thay đổi mật khẩu");
@define("_chonthemsanpham","Chọn thêm sản phẩm");
@define("_hotrothanhtoanqua","Hỗ trợ thanh toán qua");
@define("_magiamgia","Mã giảm giá");
@define("_dienmagiamgiavaoday","Điền mã giảm giá vào đây");
@define("_phivanchuyen","Phí vận chuyển");
@define("_mienphi","Miễn phí");
@define("_dabaogomthue","Đã bao gồm thuế");
@define("_hoac","Hoặc");
@define("_trovedanhmuc","Trở về danh mục");
@define("_dangxuatthanhcong","Đăng xuất thành công");
@define("_nhomatkhau","Nhớ mật khẩu");
@define("_dangkyhoacdangnhapvaotaikhoancuaban","Đăng ký hoặc đăng nhập vào tài khoản của bạn");
@define("_khachhangdadangky","Khách hàng đã đăng ký");
@define("_banlakhachhangmoichuacotaikhoan","Bạn là khách hàng mới chưa có tài khoản");
@define("_dangkyvamuahang","Đăng ký và mua hàng");
@define("_banchuacodonhangnao","Bạn chưa có đơn hàng nào");
@define("_ngaydat","Ngày đặt");
@define("_madonhang","Mã đơn hàng");
@define("_nhapmadonhang","Nhập mã đơn hàng");
@define("_chuanhapmadonhang","Bạn chưa nhập mã đơn hàng !!!");
@define("_xem","Xem");
@define("_huydonhang","Hủy đơn hàng");
@define("_bancothatsuhuydonhangnay","Bạn có thật sự muốn hủy đơn hàng này");
@define("_huydonhangnay","Hủy đơn hàng này");
@define("_thongtinnguoidathang","Thông tin người đặt hàng");
@define("_thongtinnguoinhanhang","Thông tin người nhận hàng");
@define("_quaylai","Quay lại");
@define("_chitietdonhang","Chi tiết đơn hàng");
@define("_coupleError","Vui lòng điền mã giảm giá");

@define("_linhvuchoatdong","Lĩnh vực hoạt động");
@define("_linhvuccongty","Lĩnh vực công ty");
@define("_luatsu","Luật sư");
@define("_tuvan","Tư vấn");
@define("_thuvien","Thư viện");
@define("_thongke","Thống kê");
@define("_lienhevoichungtoi","Liên hệ với chúng tôi");
@define("_theodoihoso","Theo dõi hồ sơ");
@define("_nhaphovaten","Nhập họ và tên");
@define("_nhapmahoso","Nhập mã hồ sơ");
@define("_mahoso","Mã hồ sơ");
@define("_banchuanhapmahoso","Bạn chưa nhập mã hồ sơ");
@define("_guicauhoidenchungtoi","Gửi câu hỏi đến chúng tôi");
@define("_guicauhoi","Gửi câu hỏi");
@define("_cauhoi","Câu hỏi");
@define("_dong","Đóng");
@define("_docthem","Đọc thêm");
@define("_tinkhac","Tin khác");
@define("_cosohatangkhac","Các Cơ sở hạ tầng khác");
@define("_filedinhkem","File đính kèm");
@define("_hosoError","Hồ sơ không tồn tại");
@define("_email","Email");
@define("_kiemtra","Kiểm tra");
@define("_tukhoa","Từ khóa");
@define("_hethongdaily","Hệ thống đại lý");
@define("_khongcodailynaookhuvucnay","Không có đại lý nào ở khu vực này");

@define("_duan","Dự án");
@define("_congtrinh","Công trình");
@define("_congtrinhtieubieu","Công trình tiêu biểu");
@define("_maunha","Mẫu nhà");
@define("_kientruc","Kiến trúc");
@define("_congtrinhnoibat","Công trình nổi bật");
@define("_duannoibat","Dự án tiêu biểu");
@define("_maunhadep","Mẫu nhà đẹp");
@define("_danhmuccongtrinh","Danh mục công trình");
@define("_tienichonline","Tiện ích online");
@define("_dubaothoitiet","Dự án thời tiết");
@define("_giavang","Giá vàng");
@define("_lienketweb","Liên kết web");
@define("_doitaccuachungtoi","Đối tác của chúng tôi");
@define("_xemchitiet","Xem chi tiết");
@define("_xemchitietsanpham","Xem chi tiết sản phẩm");
@define("_caccongtrinhkhac","Các công trình khác");
@define("_cacmaunhakhac","Các mẫu nhà khác");
@define("_chonlienket","Chọn liên kết");
@define("_cacduankhac","Các dự án khác");
@define("_baotribaoduong","Bảo trì bảo dưỡng");
@define("_cungungthietbivattu","Cung ứng thiết bị vật tư");
@define("_cacduan","Các dự án");
@define("_logodoitac","Logo đối tác");

@define("_hinhanhdoitac","Hình ảnh đối tác");
@define("_hinhanhduan","Hình ảnh dự án");
@define("_hinhanhsanpham","Hình ảnh sản phẩm");

@define("_guibaogiathanhcong","Gửi yêu cầu báo giá thành công, chúng tôi sẽ liên lạc với bạn sớm !");
@define("_temnhanmac","Tem nhãn mác");
@define("_quangcaokhuyenmai","Quảng cáo - Khuyến mãi");
@define("_giaiphapchonggia","Giải pháp chống giả");
@define("_giacong","Gia công");
@define("_mmtuvan","MM Tư vấn");
@define("_giay","Giấy");
@define("_kimloai","Kim loại");
@define("_loaikhac","Loại khác");
@define("_inluainluoi","In lụa (in lưới)");
@define("_incuon","In cuộn");
@define("_inbenmau","In bền màu");

@define("_veminhman","Về Minh Mẫn");
@define("_guiyeucaubaogia","Gửi yêu cầu báo giá");
@define("_huongdanguifile","Hướng dẫn gửi file");
@define("_quytrinhsanxuatmotsanpham","Quy trình sản xuất một sản phẩm");
@define("_giaohangnhantien","Giao hàng nhận tiền");
@define("_mienphigiaohang", "Miễn phí giao hàng"); 
@define("_nguyenlieuphuhop","Nguyên liệu phù hợp");
@define("_congngheapdung","Công nghệ áp dụng");
@define("_toiuusanpham","Tối ưu sản phẩm");
@define("_khachhang","Khách hàng");
@define("_homqua","Hôm qua");
@define("_ngaydang","Ngày đăng");
@define("_hantuyendung","Hạn tuyển dụng");
@define("_cactintuyendungkhac","Các tin tuyển dụng khác");
@define("_cactingioithieukhac","Các tin giới thiệu khác");
@define("_congty","Công ty");
@define("_congtyError","Vui lòng nhập công ty của bạn");
?>